#!/bin/bash
#
RETVAL=0
HERE=`pwd`
PHP="php7"
WAWAS="$PHP $HERE/runner.php"
WAWASNAME="WAWAS"
PIDFILE="$HERE/wawas.lock"
LOGFILE="$HERE/logs/wawas.log"

isrunning()
{
  if [ -f "$PIDFILE" ]; then
    return 0;
  else
    return 1;
  fi
}

start()
{
  if isrunning; then
    echo "$WAWASNAME is already running"
    return 1;
  else
    echo
    echo -n $"Starting $WAWASNAME: "
    $WAWAS >> $LOGFILE 2>&1
    RETVAL=$?
    echo
    return $RETVAL
  fi
}

stop()
{
  if isrunning; then
    echo
    echo -n $"Stopping $WAWASNAME: "
    $WAWAS -k
    RETVAL=$?
#    kill `cat $PIDFILE` >/dev/null 2>/dev/null
#    sleep 1
#    rm -f $PIDFILE
#    echo
    return $RETVAL
  else
    echo "$WAWASNAME is not running"
  fi
}

restart() {
  stop
  start
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  configtest)
    configtest
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
